import Foundation
import Testing
@testable import TurboFieldfare

/// Golden tests for the DeepSeek V4 chat framing. Every expected string in
/// this suite was generated by running the reference
/// `deepseek-ai/DeepSeek-V4-Pro` `encoding/encoding_dsv4.py`
/// (`encode_messages`) on the equivalent message list.
@Suite("V4ChatFormat")
struct V4ChatFormatTests {
    private static let bos = "<｜begin▁of▁sentence｜>"
    private static let eos = "<｜end▁of▁sentence｜>"
    private static let user = "<｜User｜>"
    private static let assistant = "<｜Assistant｜>"
    private static let d = "｜DSML｜"

    private static let weatherTool = try! V4FunctionTool(
        name: "get_weather",
        description: "Get weather",
        parametersJSON: #"{"type":"object","properties":{"city":{"type":"string"}},"required":["city"]}"#)

    private static let toolsBlock = """
        ## Tools

        You have access to a set of tools to help answer the user's question. You can invoke tools by writing a "<\(d)tool_calls>" block like the following:

        <\(d)tool_calls>
        <\(d)invoke name="$TOOL_NAME">
        <\(d)parameter name="$PARAMETER_NAME" string="true|false">$PARAMETER_VALUE</\(d)parameter>
        ...
        </\(d)invoke>
        <\(d)invoke name="$TOOL_NAME2">
        ...
        </\(d)invoke>
        </\(d)tool_calls>

        String parameters should be specified as is and set `string="true"`. For all other types (numbers, booleans, arrays, objects), pass the value in JSON format and set `string="false"`.

        If thinking_mode is enabled (triggered by <think>), you MUST output your complete reasoning inside <think>...</think> BEFORE any tool calls or final response.

        Otherwise, output directly after </think> with tool calls or final response.

        ### Available Tool Schemas

        {"name": "get_weather", "description": "Get weather", "parameters": {"type": "object", "properties": {"city": {"type": "string"}}, "required": ["city"]}}

        You MUST strictly follow the above defined tool name and parameter schemas to invoke tool calls.

        """

    @Test("Chat mode: single user turn")
    func singleUserTurn() throws {
        let p = try V4ChatFormat.encodeMessages(
            [V4Message(role: .user, content: "Hello")],
            thinkingMode: .chat)
        #expect(p == "\(Self.bos)\(Self.user)Hello\(Self.assistant)</think>")
    }

    @Test("Chat mode: system + user")
    func systemAndUser() throws {
        let p = try V4ChatFormat.encodeMessages(
            [V4Message(role: .system, content: "You are helpful."),
             V4Message(role: .user, content: "Hi")],
            thinkingMode: .chat)
        #expect(p == "\(Self.bos)You are helpful.\(Self.user)Hi\(Self.assistant)</think>")
    }

    @Test("Chat mode: multi-turn closes assistant turns with EOS")
    func multiTurn() throws {
        let p = try V4ChatFormat.encodeMessages(
            [V4Message(role: .user, content: "A"),
             V4Message(role: .assistant, content: "B"),
             V4Message(role: .user, content: "C")],
            thinkingMode: .chat)
        #expect(p == "\(Self.bos)\(Self.user)A\(Self.assistant)</think>B\(Self.eos)\(Self.user)C\(Self.assistant)</think>")
    }

    @Test("Chat mode: tool schemas are injected into the system prompt")
    func toolsInSystemPrompt() throws {
        let p = try V4ChatFormat.encodeMessages(
            [V4Message(role: .system, content: "You are helpful.", tools: [Self.weatherTool]),
             V4Message(role: .user, content: "weather in Paris?")],
            thinkingMode: .chat)
        #expect(p == "\(Self.bos)You are helpful.\n\n\(Self.toolsBlock)\(Self.user)weather in Paris?\(Self.assistant)</think>")
    }

    @Test("Chat mode: full tool round trip (call + merged result)")
    func toolRoundTrip() throws {
        let p = try V4ChatFormat.encodeMessages(
            [V4Message(role: .system, content: "S", tools: [Self.weatherTool]),
             V4Message(role: .user, content: "weather in Paris?"),
             V4Message(role: .assistant, content: "",
                       toolCalls: [V4ToolCallSpec(id: "c1", name: "get_weather",
                                                  arguments: #"{"city": "Paris"}"#)]),
             V4Message(role: .tool, content: "sunny, 22C", toolCallID: "c1"),
             V4Message(role: .user, content: "thanks")],
            thinkingMode: .chat)
        #expect(p == "\(Self.bos)S\n\n\(Self.toolsBlock)\(Self.user)weather in Paris?\(Self.assistant)</think>"
            + "\n\n<\(Self.d)tool_calls>\n<\(Self.d)invoke name=\"get_weather\">\n"
            + "<\(Self.d)parameter name=\"city\" string=\"true\">Paris</\(Self.d)parameter>\n"
            + "</\(Self.d)invoke>\n</\(Self.d)tool_calls>\(Self.eos)"
            + "\(Self.user)<tool_result>sunny, 22C</tool_result>\n\nthanks\(Self.assistant)</think>")
    }

    @Test("Thinking mode: prior reasoning dropped, generation prompt opens <think>")
    func thinkingModeDropsPriorReasoning() throws {
        let p = try V4ChatFormat.encodeMessages(
            [V4Message(role: .user, content: "Q"),
             V4Message(role: .assistant, content: "A1", reasoningContent: "because"),
             V4Message(role: .user, content: "Q2")],
            thinkingMode: .thinking)
        #expect(p == "\(Self.bos)\(Self.user)Q\(Self.assistant)</think>A1\(Self.eos)\(Self.user)Q2\(Self.assistant)<think>")
    }

    @Test("Thinking mode: reasoning kept after the last user message")
    func thinkingKeepsLatestReasoning() throws {
        let p = try V4ChatFormat.encodeMessages(
            [V4Message(role: .user, content: "Q"),
             V4Message(role: .assistant, content: "A1", reasoningContent: "r1"),
             V4Message(role: .user, content: "Q2"),
             V4Message(role: .assistant, content: "A2", reasoningContent: "r2", woEOS: true)],
            thinkingMode: .thinking)
        #expect(p == "\(Self.bos)\(Self.user)Q\(Self.assistant)</think>A1\(Self.eos)\(Self.user)Q2\(Self.assistant)<think>r2</think>A2")
    }

    @Test("Thinking mode with tools keeps prior reasoning")
    func thinkingWithToolsKeepsReasoning() throws {
        let p = try V4ChatFormat.encodeMessages(
            [V4Message(role: .system, content: "S", tools: [Self.weatherTool]),
             V4Message(role: .user, content: "Q"),
             V4Message(role: .assistant, content: "A1", reasoningContent: "r1"),
             V4Message(role: .user, content: "Q2")],
            thinkingMode: .thinking)
        // Tools present => drop_thinking is forced off.
        #expect(p.contains("<think>r1</think>A1") || p.contains("r1</think>A1"))
        #expect(p.contains("r1"))
        #expect(p.hasSuffix("\(Self.assistant)<think>"))
    }

    @Test("Reasoning effort max prepends the fixed prefix")
    func reasoningEffortMax() throws {
        let p = try V4ChatFormat.encodeMessages(
            [V4Message(role: .user, content: "Q")],
            thinkingMode: .thinking,
            reasoningEffort: .max)
        #expect(p == "\(Self.bos)Reasoning Effort: Absolute maximum with no shortcuts permitted.\n"
            + "You MUST be very thorough in your thinking and comprehensively decompose the problem to resolve the root cause, rigorously stress-testing your logic against all potential paths, edge cases, and adversarial scenarios.\n"
            + "Explicitly write out your entire deliberation process, documenting every intermediate step, considered alternative, and rejected hypothesis to ensure absolutely no assumption is left unchecked.\n\n"
            + "\(Self.user)Q\(Self.assistant)<think>")
    }

    @Test("Developer messages render with the User prefix")
    func developerRole() throws {
        let p = try V4ChatFormat.encodeMessages(
            [V4Message(role: .developer, content: "dev note"),
             V4Message(role: .user, content: "Hi")],
            thinkingMode: .chat)
        #expect(p == "\(Self.bos)\(Self.user)dev note\(Self.user)Hi\(Self.assistant)</think>")
    }

    @Test("latest_reminder role renders with its own prefix")
    func latestReminder() throws {
        let p = try V4ChatFormat.encodeMessages(
            [V4Message(role: .user, content: "Hi"),
             V4Message(role: .assistant, content: "ok"),
             V4Message(role: .latestReminder, content: "remind me")],
            thinkingMode: .chat)
        #expect(p == "\(Self.bos)\(Self.user)Hi\(Self.assistant)</think>ok\(Self.eos)<｜latest_reminder｜>remind me")
    }

    @Test("Non-action task appends the task token directly")
    func taskQuery() throws {
        let p = try V4ChatFormat.encodeMessages(
            [V4Message(role: .user, content: "Hi", task: .query)],
            thinkingMode: .chat)
        #expect(p == "\(Self.bos)\(Self.user)Hi<｜query｜>")
    }

    @Test("Action task appends assistant + think token + action token")
    func taskAction() throws {
        let p = try V4ChatFormat.encodeMessages(
            [V4Message(role: .user, content: "Hi", task: .action)],
            thinkingMode: .chat)
        #expect(p == "\(Self.bos)\(Self.user)Hi\(Self.assistant)</think><｜action｜>")
    }

    @Test("DSML argument types: string raw, everything else json.dumps")
    func dsmlArgumentTypes() throws {
        let p = try V4ChatFormat.encodeMessages(
            [V4Message(role: .assistant, content: "",
                       toolCalls: [V4ToolCallSpec(
                        name: "f",
                        arguments: #"{"s": "txt", "n": 5, "b": true, "arr": [1, 2], "obj": {"k": "v"}, "nil": null}"#)], woEOS: true)],
            thinkingMode: .chat)
        let d = Self.d
        #expect(p == "\(Self.bos)\n\n<\(d)tool_calls>\n<\(d)invoke name=\"f\">\n"
            + "<\(d)parameter name=\"s\" string=\"true\">txt</\(d)parameter>\n"
            + "<\(d)parameter name=\"n\" string=\"false\">5</\(d)parameter>\n"
            + "<\(d)parameter name=\"b\" string=\"false\">true</\(d)parameter>\n"
            + "<\(d)parameter name=\"arr\" string=\"false\">[1, 2]</\(d)parameter>\n"
            + "<\(d)parameter name=\"obj\" string=\"false\">{\"k\": \"v\"}</\(d)parameter>\n"
            + "<\(d)parameter name=\"nil\" string=\"false\">null</\(d)parameter>\n"
            + "</\(d)invoke>\n</\(d)tool_calls>")
    }

    @Test("Non-JSON arguments fall back to a single arguments string parameter")
    func dsmlBadJSONArguments() throws {
        let p = try V4ChatFormat.encodeMessages(
            [V4Message(role: .assistant, content: "",
                       toolCalls: [V4ToolCallSpec(name: "f", arguments: "not json")], woEOS: true)],
            thinkingMode: .chat)
        let d = Self.d
        #expect(p == "\(Self.bos)\n\n<\(d)tool_calls>\n<\(d)invoke name=\"f\">\n"
            + "<\(d)parameter name=\"arguments\" string=\"true\">not json</\(d)parameter>\n"
            + "</\(d)invoke>\n</\(d)tool_calls>")
    }

    @Test("Multiple invokes render in order inside one tool_calls block")
    func multipleInvokes() throws {
        let p = try V4ChatFormat.encodeMessages(
            [V4Message(role: .assistant, content: "calling",
                       toolCalls: [V4ToolCallSpec(name: "f", arguments: #"{"a": 1}"#),
                                   V4ToolCallSpec(name: "g", arguments: #"{"b": "x"}"#)])],
            thinkingMode: .chat)
        let d = Self.d
        #expect(p == "\(Self.bos)calling\n\n<\(d)tool_calls>\n"
            + "<\(d)invoke name=\"f\">\n<\(d)parameter name=\"a\" string=\"false\">1</\(d)parameter>\n</\(d)invoke>\n"
            + "<\(d)invoke name=\"g\">\n<\(d)parameter name=\"b\" string=\"true\">x</\(d)parameter>\n</\(d)invoke>\n"
            + "</\(d)tool_calls>\(Self.eos)")
    }

    @Test("Response format schema appended to system content")
    func responseFormat() throws {
        let p = try V4ChatFormat.encodeMessages(
            [V4Message(role: .system, content: "S",
                       responseFormat: .object([("type", .string("json_object"))])),
             V4Message(role: .user, content: "Hi")],
            thinkingMode: .chat)
        #expect(p == "\(Self.bos)S\n\n## Response Format:\n\nYou MUST strictly adhere to the following schema to reply:\n"
            + "{\"type\": \"json_object\"}\(Self.user)Hi\(Self.assistant)</think>")
    }

    @Test("Context messages are not re-rendered and suppress BOS")
    func contextMessages() throws {
        let p = try V4ChatFormat.encodeMessages(
            [V4Message(role: .user, content: "new")],
            context: [V4Message(role: .user, content: "old"),
                      V4Message(role: .assistant, content: "ans")],
            thinkingMode: .chat)
        #expect(p == "\(Self.user)new\(Self.assistant)</think>")
    }

    @Test("Tool results are sorted by assistant call order")
    func toolResultSorting() throws {
        let p = try V4ChatFormat.encodeMessages(
            [V4Message(role: .assistant, content: "",
                       toolCalls: [V4ToolCallSpec(id: "a", name: "f", arguments: "{}"),
                                   V4ToolCallSpec(id: "b", name: "g", arguments: "{}")]),
             V4Message(role: .tool, content: "result-b", toolCallID: "b"),
             V4Message(role: .tool, content: "result-a", toolCallID: "a"),
             V4Message(role: .user, content: "go on")],
            thinkingMode: .chat)
        #expect(p.contains("<tool_result>result-a</tool_result>\n\n<tool_result>result-b</tool_result>\n\ngo on"))
    }

    @Test("Stop tokens: EOS only")
    func stopTokens() {
        #expect(V4ChatFormat.stopTokenIDs() == [1])
        #expect(V4ChatFormat.stopTokenIDs(.pinned) == [V4SpecialTokenIDs.pinned.eos])
    }

    @Test("Special token table loads from tokenizer.json added_tokens")
    func specialTokenLoader() throws {
        let fixture = V4TestFixtures.tokenizerJSONURL
        guard let url = fixture else {
            // Fixture not present; pinned table is still validated by the
            // compat suite when the fixture is available.
            return
        }
        let loaded = try V4SpecialTokenIDs.load(fromTokenizerJSON: url)
        #expect(loaded == .pinned)
    }
}

/// Locates the DeepSeek V4 tokenizer fixture (scratch/v4f-recon) when present.
enum V4TestFixtures {
    static var tokenizerJSONURL: URL? {
        let fileManager = FileManager.default
        var candidates: [URL] = []
        if let override = ProcessInfo.processInfo.environment["V4F_TOKENIZER_DIR"], !override.isEmpty {
            candidates.append(URL(fileURLWithPath: override))
        }
        candidates.append(URL(fileURLWithPath: fileManager.currentDirectoryPath)
            .appendingPathComponent("scratch/v4f-recon", isDirectory: true))
        for candidate in candidates {
            let tokenizerJSON = candidate.appendingPathComponent("tokenizer.json")
            if fileManager.fileExists(atPath: tokenizerJSON.path) {
                return tokenizerJSON
            }
        }
        return nil
    }
}
